DE Translation
opentx/opentx pull request #5892
Opened 2018-05-17 07:34 UTC by LapinFou

@hrenz did update the DE translation. He followed this tutorial → https://github.com/opentx/opentx/wiki/Flow-for-the-Translators
But, since he is not a member of OpenTX project, he has not been able to push his modifications.
So, I've done it.
At some point, I should update the tutorial in order to explain how to create some PR from a cloned repo.
In other hand, if @hrenz is OK to support and maintain de DE translation, maybe he could be part of the OTX team?

If you do update the translator credit field, here is the information:
**[de] Helmut Renz (hrenz)**

2018-05-20 12:40 UTC, schwabe requested changes
I have gone through all the changes. 

I thought that having an empty translation means that the translation is also empty but it seems that the original English is then used instead. 

I am not a fan of this way of marking these strings as finished being translated if there is no real translation but that is ultimately up to however maintains the translations.

There some minor things I noticed with the translation that I commend on each string.

2018-05-20 12:40 UTC, schwabe commented on companion/src/translations/companion_de.ts
> +        <translation>Auswahl der Ansagespreche.
Vielleicht eher Sprachausgabe?

2018-05-20 12:40 UTC, schwabe commented on companion/src/translations/companion_de.ts
> +        <translation></translation>
Am besten auf unfishined lassen, wenn es nicht übersetzt ist, so bekommt der Nutzt statt der Englischen nur eine leere Fehlermeldung

2018-05-20 12:40 UTC, schwabe commented on companion/src/translations/companion_de.ts
> +        <translation>Ungültige Binär EEPROM Datei %1</translation>
Vom Gefühl würde ich binäre EEPROM-Datei sagen

2018-05-20 12:40 UTC, schwabe commented on companion/src/translations/companion_de.ts
> +        <translation>Neg Bereich</translation>
Im Dialog sollte genug Platz sein um das auszuschreiben. Ich glaube Spanne oder Umfang könnte hier auch passen

2018-05-20 12:40 UTC, schwabe commented on companion/src/translations/companion_de.ts
> -        <translation type="unfinished">Mitte Wert</translation>
Wert Mittelstellung

2018-05-20 12:40 UTC, schwabe commented on companion/src/translations/companion_de.ts
> +        <translation></translation>
Leere Übersetzung, siehe oben

2018-05-20 12:40 UTC, schwabe commented on companion/src/translations/companion_de.ts
> +        <translation></translation>
Leere Übersetzung, siehe oben

2018-05-20 12:40 UTC, schwabe commented on companion/src/translations/companion_de.ts
> +        <translation></translation>
Leere Übersetzung, siehe oben

2018-05-20 12:40 UTC, schwabe commented on companion/src/translations/companion_de.ts
> +        <translation></translation>
Leere Übersetzung, siehe oben

2018-05-20 12:40 UTC, schwabe commented on companion/src/translations/companion_de.ts
> +        <translation>Fenster verfügbar</translation>
Menu ist nicht ganz gleiche wie Fenster.

2018-05-20 12:40 UTC, schwabe commented on companion/src/translations/companion_de.ts
> +        <translation></translation>
Leere Übersetzung, siehe oben

2018-05-20 12:40 UTC, schwabe commented on companion/src/translations/companion_de.ts
> +        <translation></translation>
Leere Übersetzung, siehe oben

2018-05-20 12:40 UTC, schwabe commented on companion/src/translations/companion_de.ts
> +        <translation></translation>
Leere Übersetzung, siehe oben

2018-05-20 12:40 UTC, schwabe commented on companion/src/translations/companion_de.ts
> -        <translation type="unfinished"></translation>
Leere Übersetzung, siehe oben

2018-05-20 12:40 UTC, schwabe commented on companion/src/translations/companion_de.ts
> +        <translation></translation>
Leere Übersetzung, siehe oben

2018-05-20 12:40 UTC, schwabe commented on companion/src/translations/companion_de.ts
> +        <translation></translation>
Leere Übersetzung, siehe oben

2018-05-20 12:40 UTC, schwabe commented on companion/src/translations/companion_de.ts
> +        <translation></translation>
Leere Übersetzung, siehe oben

2018-05-20 12:40 UTC, schwabe commented on companion/src/translations/companion_de.ts
> +        <translation></translation>
Leere Übersetzung, siehe oben

2018-05-20 12:40 UTC, schwabe commented on companion/src/translations/companion_de.ts
> +        <translation></translation>
Leere Übersetzung, siehe oben

2018-05-20 12:40 UTC, schwabe commented on companion/src/translations/companion_de.ts
> +        <translation></translation>
Leere Übersetzung, siehe oben

2018-05-20 12:40 UTC, schwabe commented on companion/src/translations/companion_de.ts
> +        <translation>Sumulator Fehler</translation>
Tippfehler

2018-05-20 12:40 UTC, schwabe commented on companion/src/translations/companion_de.ts
> +        <translation>Fehler während  Start des Simulator.</translation>
Simulatorstart fehlgechlagen?

2018-05-20 12:40 UTC, schwabe commented on companion/src/translations/companion_de.ts
> +        <translation></translation>
Leere Übersetzung, siehe oben

2018-05-20 12:40 UTC, schwabe commented on companion/src/translations/companion_de.ts
> +        <translation></translation>
Leere Übersetzung, siehe oben

2018-05-20 12:40 UTC, schwabe commented on companion/src/translations/companion_de.ts
> +        <translation>OK verstanden.</translation>
Okay, verstanden

2018-05-20 12:40 UTC, schwabe commented on companion/src/translations/companion_de.ts
> +        <translation></translation>
Leere Übersetzung, siehe oben

2018-05-20 12:40 UTC, schwabe commented on companion/src/translations/companion_de.ts
> +        <translation>Nicht genug freie Punkte im EEPROM um die Kurve zu speichern.</translation>
Nicht genügend freie Stützstellen  im EEProm um die Kurzve zu speichern.

2018-05-20 12:40 UTC, schwabe commented on companion/src/translations/companion_de.ts
> +        <translation></translation>
Leere Übersetzung, siehe oben

2018-05-20 12:40 UTC, schwabe commented on companion/src/translations/companion_de.ts
> +        <translation>Set Timer %1</translation>
Setze Timer %1

2018-05-20 12:40 UTC, schwabe commented on companion/src/translations/companion_de.ts
> +        <translation>Start Script</translation>
Starte Skript

2018-05-20 12:40 UTC, schwabe commented on companion/src/translations/companion_de.ts
> +        <translation>Lautstärke Gesamt</translation>
Gesamtlautstärke

2018-05-20 12:40 UTC, schwabe commented on companion/src/translations/companion_de.ts
> +        <translation>LCD Beleuchtung</translation>
LCD-Beleuchtung oder Hintergrundbeleuchtung

2018-05-20 12:40 UTC, schwabe commented on companion/src/translations/companion_de.ts
> +        <translation>Hintergrund Musik</translation>
Hintergrundmusik

2018-05-20 12:40 UTC, schwabe commented on companion/src/translations/companion_de.ts
> +        <translation>Hintergrund Musik Pause</translation>
Pausiere Hintergrundmusik

2018-05-20 12:40 UTC, schwabe commented on companion/src/translations/companion_de.ts
>      </message>
Leere Übersetzung, siehe oben

2018-05-20 12:40 UTC, schwabe commented on companion/src/translations/companion_de.ts
> +        <translation></translation>
Leere Übersetzung, siehe oben

2018-05-20 12:40 UTC, schwabe commented on companion/src/translations/companion_de.ts
> +        <translation></translation>
Leere Übersetzung, siehe oben

2018-05-20 12:40 UTC, schwabe commented on companion/src/translations/companion_de.ts
> +        <translation>Decr:</translation>
Dekr: von dekrementieren.

2018-05-20 12:40 UTC, schwabe commented on companion/src/translations/companion_de.ts
> +        <translation>Incr:</translation>
Inkr: von Inkrementieren.

2018-05-20 12:40 UTC, schwabe commented on companion/src/translations/companion_de.ts
> +        <translation></translation>
Leere Übersetzung, siehe oben

2018-05-20 12:40 UTC, schwabe commented on companion/src/translations/companion_de.ts
> -        <translation type="unfinished"></translation>
Leere Übersetzung, siehe oben

2018-05-20 12:40 UTC, schwabe commented on companion/src/translations/companion_de.ts
> +        <translation>Increment</translation>
mit k

2018-05-20 12:40 UTC, schwabe commented on companion/src/translations/companion_de.ts
> +        <translation>Profil Bild</translation>
Profilbild

2018-05-20 12:40 UTC, schwabe commented on companion/src/translations/companion_de.ts
> +        <translation></translation>
Leere Übersetzung, siehe oben

2018-05-20 12:40 UTC, schwabe commented on companion/src/translations/companion_de.ts
> +        <translation></translation>
Leere Übersetzung, siehe oben

2018-05-20 12:40 UTC, schwabe commented on companion/src/translations/companion_de.ts
> +        <translation>OpenTX kann nur max %1 Punkte für alle Kurven</translation>
OpenTX unterstützt nur maximal %1 Stützstellen für alle Kurven

2018-05-20 12:40 UTC, schwabe commented on companion/src/translations/companion_de.ts
> +        <translation></translation>
Leere Übersetzung, siehe oben

2018-05-20 12:40 UTC, schwabe commented on companion/src/translations/companion_de.ts
> +        <translation>OpenTx kann nicht diese Anzahl von Kanälen</translation>
Das hört sich falsch an an. OpenTX unterstützt diese Anzahl an Kanälen nicht.

2018-05-20 12:40 UTC, schwabe commented on companion/src/translations/companion_de.ts
> +        <translation></translation>
Leere Übersetzung, siehe oben

2018-05-20 12:40 UTC, schwabe commented on companion/src/translations/companion_de.ts
> +        <translation> (q%1)</translation>
Tippfehler

2018-05-20 12:40 UTC, schwabe commented on companion/src/translations/companion_de.ts
> +        <translation>Scalierung</translation>
wenn Skalierung dann mit k, aber ich glaube Gewichtung ist das richtige hier oder wird das sonst anders übersetzt?

2018-05-20 12:40 UTC, schwabe commented on companion/src/translations/companion_de.ts
> +        <translation>Kanalwerte Anzeige in us statt %</translation>
hier kann man ruhig µs verwenden, Companion unterstützt Sonderzeichen

2018-05-20 12:40 UTC, schwabe commented on companion/src/translations/companion_de.ts
> +        <translation>Keine Überschrebefunktion verfügbar</translation>
Typo

2018-05-20 12:40 UTC, schwabe commented on companion/src/translations/companion_de.ts
> +        <translation>Unterstüzung für DSM2 Modul mit PPM-Signal anstatt echtem seriellem Signal</translation>
... echten ...

2018-05-20 12:40 UTC, schwabe commented on companion/src/translations/companion_de.ts
> +        <translation>Kein GPS</translation>
Keine GPS Unterstützung

2018-05-20 12:40 UTC, schwabe commented on companion/src/translations/companion_de.ts
> +        <translation>Das Profil-Image %1 ist ungültig.</translation>
Inkonsistenz hier oben war es Profilbild

2018-05-20 12:40 UTC, schwabe commented on companion/src/translations/companion_de.ts
> +        <translation>Neue Firmware ist nicht mit der schon installierten compatibel!</translation>
kompatibel

2018-05-20 12:40 UTC, schwabe commented on companion/src/translations/companion_de.ts
> +        <translation>Falshen fertig</translation>
Typo

2018-05-20 12:40 UTC, schwabe commented on companion/src/translations/companion_de.ts
> +        <translation>Polish</translation>
Polnisch

2018-05-20 12:40 UTC, schwabe commented on companion/src/translations/companion_de.ts
> +        <translation>Instance</translation>
Instanz

2018-05-20 12:40 UTC, schwabe commented on companion/src/translations/companion_de.ts
> +        <translation>Sub Typ</translation>
Subtyp

2018-05-20 12:40 UTC, schwabe commented on companion/src/translations/companion_de.ts
> +        <translation>Swash</translation>
Taumelscheibe

2018-05-20 12:40 UTC, schwabe commented on companion/src/translations/companion_de.ts
> +        <translation>Scalierung</translation>
mit k

2018-05-20 12:40 UTC, schwabe commented on companion/src/translations/companion_de.ts
> +        <translation>CC2500 Frequenzfeinabgleich Tuner</translation>
Das Tuner kann hier weg

2018-05-20 12:40 UTC, schwabe commented on companion/src/translations/companion_de.ts
> +        <translation>Abbruch</translation>
Abbrechen ist üblicher

2018-05-20 12:40 UTC, schwabe commented on companion/src/translations/companion_de.ts
> +        <translation>Companion Software Stände</translation>
Companion Versionshinweise

2018-05-20 15:28 UTC, hrenz commented
Hallo,


ja bitte abändern, wenn besssere, eindeutigere Bezeichner vorhanden.


Musste die ganzen Änderungen an einem Abend machen,
konnte nicht alles gegenchecken.


Maches ist besser es in englisch zu lassen.



mfg
hrenz

 

 

 

-----Ursprüngliche Mitteilung----- 
Von: Arne Schwabe <notifications@github.com>
An: opentx/opentx <opentx@noreply.github.com>
Cc: hrenz <hrenz62961@aol.com>; Mention <mention@noreply.github.com>
Verschickt: So, 20. Mai 2018 14:41
Betreff: Re: [opentx/opentx] DE Translation (#5892)



@schwabe requested changes on this pull request.
I have gone through all the changes.
I thought that having an empty translation means that the translation is also empty but it seems that the original English is then used instead.
I am not a fan of this way of marking these strings as finished being translated if there is no real translation but that is ultimately up to however maintains the translations.
There some minor things I noticed with the translation that I commend on each string.

In companion/src/translations/companion_de.ts:
> @@ -355,7 +355,8 @@ Mode 4:
         <location filename="../apppreferencesdialog.ui" line="314"/>
         <source>Set voice language.
 May be different from firmware language</source>
-        <translation type="unfinished"></translation>
+        <translation>Auswahl der Ansagespreche.

Vielleicht eher Sprachausgabe?

In companion/src/translations/companion_de.ts:
> @@ -596,7 +597,7 @@ May be different from firmware language</source>
     <message>
         <location filename="../apppreferencesdialog.cpp" line="117"/>
         <source><p><b>You cannot switch Radio Type or change Build Options while there are unsaved file changes. What do you wish to do?</b></p> <ul><li><i>Save All</i> - Save any open file(s) before saving Settings.<li><li><i>Reset</i> - Revert to the previous Radio Type and Build Options before saving Settings.</li><li><i>Cancel</i> - Return to the Settings editor dialog.</li></ul></source>
-        <translation type="unfinished"></translation>
+        <translation></translation>

Am besten auf unfishined lassen, wenn es nicht übersetzt ist, so bekommt der Nutzt statt der Englischen nur eine leere Fehlermeldung

In companion/src/translations/companion_de.ts:
>  %2.</translation>
     </message>
     <message>
         <location filename="../storage/bineeprom.cpp" line="107"/>
         <source>Invalid binary EEPROM file %1</source>
-        <translation type="unfinished"></translation>
+        <translation>Ungültige Binär EEPROM Datei %1</translation>

Vom Gefühl würde ich binäre EEPROM-Datei sagen

In companion/src/translations/companion_de.ts:
>      </message>
 </context>
 <context>
     <name>CalibrationPanel</name>
     <message>
         <location filename="../generaledit/calibration.cpp" line="44"/>
         <source>Negative span</source>
-        <translation type="unfinished">Neg Bereich</translation>
+        <translation>Neg Bereich</translation>

Im Dialog sollte genug Platz sein um das auszuschreiben. Ich glaube Spanne oder Umfang könnte hier auch passen

In companion/src/translations/companion_de.ts:
>      </message>
     <message>
         <location filename="../generaledit/calibration.cpp" line="44"/>
         <source>Mid value</source>
-        <translation type="unfinished">Mitte Wert</translation>

Wert Mittelstellung

In companion/src/translations/companion_de.ts:
>      </message>
 </context>
 <context>
     <name>CategorizedStorageFormat</name>
     <message>
         <location filename="../storage/categorized.cpp" line="28"/>
         <source>Can't extract RADIO/radio.bin</source>
-        <translation type="unfinished"></translation>
+        <translation></translation>

Leere Übersetzung, siehe oben

In companion/src/translations/companion_de.ts:
>      </message>
     <message>
         <location filename="../storage/categorized.cpp" line="41"/>
         <source>Can't extract RADIO/models.txt</source>
-        <translation type="unfinished"></translation>
+        <translation></translation>

Leere Übersetzung, siehe oben

In companion/src/translations/companion_de.ts:
>      </message>
     <message>
         <location filename="../storage/categorized.cpp" line="85"/>
         <source>Can't extract %1</source>
-        <translation type="unfinished"></translation>
+        <translation></translation>

Leere Übersetzung, siehe oben

In companion/src/translations/companion_de.ts:
>      </message>
     <message>
         <location filename="../storage/categorized.cpp" line="92"/>
         <source>Error loading models</source>
-        <translation type="unfinished"></translation>
+        <translation></translation>

Leere Übersetzung, siehe oben

In companion/src/translations/companion_de.ts:
>      </message>
     <message>
         <location filename="../modeledit/channels.cpp" line="129"/>
         <source>Popup menu available</source>
-        <translation type="unfinished"></translation>
+        <translation>Fenster verfügbar</translation>

Menu ist nicht ganz gleiche wie Fenster.

In companion/src/translations/companion_de.ts:
>      </message>
     <message>
         <location filename="../modeledit/checklistdialog.ui" line="88"/>
         <source>&Import...</source>
-        <translation type="unfinished"></translation>
+        <translation></translation>

Leere Übersetzung, siehe oben

In companion/src/translations/companion_de.ts:
>      </message>
     <message>
         <location filename="../modeledit/checklistdialog.ui" line="101"/>
         <source>&Cancel</source>
-        <translation type="unfinished"></translation>
+        <translation></translation>

Leere Übersetzung, siehe oben

In companion/src/translations/companion_de.ts:
>      </message>
     <message>
         <location filename="../modeledit/checklistdialog.ui" line="114"/>
         <source>&OK</source>
-        <translation type="unfinished"></translation>
+        <translation></translation>

Leere Übersetzung, siehe oben

In companion/src/translations/companion_de.ts:
>      </message>
     <message>
         <location filename="../modeledit/checklistdialog.ui" line="129"/>
         <source>Please note, the maximum width displayable is radio model limited. Also, renaming the model will break the link to this checklist file.</source>
-        <translation type="unfinished"></translation>

Leere Übersetzung, siehe oben

In companion/src/translations/companion_de.ts:
>      </message>
     <message>
         <location filename="../modeledit/checklistdialog.cpp" line="65"/>
         <source>Open Checklist</source>
-        <translation type="unfinished"></translation>
+        <translation></translation>

Leere Übersetzung, siehe oben

In companion/src/translations/companion_de.ts:
>      </message>
     <message>
         <location filename="../modeledit/checklistdialog.cpp" line="65"/>
         <source>Checklist Files (*.txt)</source>
-        <translation type="unfinished"></translation>
+        <translation></translation>

Leere Übersetzung, siehe oben

In companion/src/translations/companion_de.ts:
> @@ -923,38 +925,40 @@ May be different from firmware language</source>
         <location filename="../modeledit/checklistdialog.cpp" line="102"/>
         <location filename="../modeledit/checklistdialog.cpp" line="110"/>
         <source>Model Checklist</source>
-        <translation type="unfinished"></translation>
+        <translation></translation>

Leere Übersetzung, siehe oben

In companion/src/translations/companion_de.ts:
>      </message>
     <message>
         <location filename="../modeledit/checklistdialog.cpp" line="76"/>
         <source>Cannot open file for writing %1:
 %2.</source>
-        <translation type="unfinished"></translation>
+        <translation></translation>

Leere Übersetzung, siehe oben

In companion/src/translations/companion_de.ts:
> @@ -963,77 +967,77 @@ May be different from firmware language</source>
         <location filename="../comp [...]

2018-05-20 15:58 UTC, hrenz commented
Hallo Arne,

 

 bei Inputs für Telemetriewerte gibt es das Feld "Skalierung"
Das ist für die %-Umrechnung, darum die Unterscheidung zu normalen Gewichtung 



Gewichtung und Offset gibt es dort ja auch noch



-------------------------------


Sollte man nicht grundätzlcih umstellen auf


Sei -->  SR
Höh --> HR
Que --> QR

Gas --> GAS


So wie bei FROS, Graupner, Futaba, Spektrum, usw.

und da das "ö" bei Höh ja immer noch nicht dargestellt wird



mfg
helle
 

 

-----Ursprüngliche Mitteilung----- 
Von: Arne Schwabe <notifications@github.com>
An: opentx/opentx <opentx@noreply.github.com>
Cc: hrenz <hrenz62961@aol.com>; Mention <mention@noreply.github.com>
Verschickt: So, 20. Mai 2018 14:41
Betreff: Re: [opentx/opentx] DE Translation (#5892)



@schwabe requested changes on this pull request.
I have gone through all the changes.
I thought that having an empty translation means that the translation is also empty but it seems that the original English is then used instead.
I am not a fan of this way of marking these strings as finished being translated if there is no real translation but that is ultimately up to however maintains the translations.
There some minor things I noticed with the translation that I commend on each string.

In companion/src/translations/companion_de.ts:
> @@ -355,7 +355,8 @@ Mode 4:
         <location filename="../apppreferencesdialog.ui" line="314"/>
         <source>Set voice language.
 May be different from firmware language</source>
-        <translation type="unfinished"></translation>
+        <translation>Auswahl der Ansagespreche.

Vielleicht eher Sprachausgabe?

In companion/src/translations/companion_de.ts:
> @@ -596,7 +597,7 @@ May be different from firmware language</source>
     <message>
         <location filename="../apppreferencesdialog.cpp" line="117"/>
         <source><p><b>You cannot switch Radio Type or change Build Options while there are unsaved file changes. What do you wish to do?</b></p> <ul><li><i>Save All</i> - Save any open file(s) before saving Settings.<li><li><i>Reset</i> - Revert to the previous Radio Type and Build Options before saving Settings.</li><li><i>Cancel</i> - Return to the Settings editor dialog.</li></ul></source>
-        <translation type="unfinished"></translation>
+        <translation></translation>

Am besten auf unfishined lassen, wenn es nicht übersetzt ist, so bekommt der Nutzt statt der Englischen nur eine leere Fehlermeldung

In companion/src/translations/companion_de.ts:
>  %2.</translation>
     </message>
     <message>
         <location filename="../storage/bineeprom.cpp" line="107"/>
         <source>Invalid binary EEPROM file %1</source>
-        <translation type="unfinished"></translation>
+        <translation>Ungültige Binär EEPROM Datei %1</translation>

Vom Gefühl würde ich binäre EEPROM-Datei sagen

In companion/src/translations/companion_de.ts:
>      </message>
 </context>
 <context>
     <name>CalibrationPanel</name>
     <message>
         <location filename="../generaledit/calibration.cpp" line="44"/>
         <source>Negative span</source>
-        <translation type="unfinished">Neg Bereich</translation>
+        <translation>Neg Bereich</translation>

Im Dialog sollte genug Platz sein um das auszuschreiben. Ich glaube Spanne oder Umfang könnte hier auch passen

In companion/src/translations/companion_de.ts:
>      </message>
     <message>
         <location filename="../generaledit/calibration.cpp" line="44"/>
         <source>Mid value</source>
-        <translation type="unfinished">Mitte Wert</translation>

Wert Mittelstellung

In companion/src/translations/companion_de.ts:
>      </message>
 </context>
 <context>
     <name>CategorizedStorageFormat</name>
     <message>
         <location filename="../storage/categorized.cpp" line="28"/>
         <source>Can't extract RADIO/radio.bin</source>
-        <translation type="unfinished"></translation>
+        <translation></translation>

Leere Übersetzung, siehe oben

In companion/src/translations/companion_de.ts:
>      </message>
     <message>
         <location filename="../storage/categorized.cpp" line="41"/>
         <source>Can't extract RADIO/models.txt</source>
-        <translation type="unfinished"></translation>
+        <translation></translation>

Leere Übersetzung, siehe oben

In companion/src/translations/companion_de.ts:
>      </message>
     <message>
         <location filename="../storage/categorized.cpp" line="85"/>
         <source>Can't extract %1</source>
-        <translation type="unfinished"></translation>
+        <translation></translation>

Leere Übersetzung, siehe oben

In companion/src/translations/companion_de.ts:
>      </message>
     <message>
         <location filename="../storage/categorized.cpp" line="92"/>
         <source>Error loading models</source>
-        <translation type="unfinished"></translation>
+        <translation></translation>

Leere Übersetzung, siehe oben

In companion/src/translations/companion_de.ts:
>      </message>
     <message>
         <location filename="../modeledit/channels.cpp" line="129"/>
         <source>Popup menu available</source>
-        <translation type="unfinished"></translation>
+        <translation>Fenster verfügbar</translation>

Menu ist nicht ganz gleiche wie Fenster.

In companion/src/translations/companion_de.ts:
>      </message>
     <message>
         <location filename="../modeledit/checklistdialog.ui" line="88"/>
         <source>&Import...</source>
-        <translation type="unfinished"></translation>
+        <translation></translation>

Leere Übersetzung, siehe oben

In companion/src/translations/companion_de.ts:
>      </message>
     <message>
         <location filename="../modeledit/checklistdialog.ui" line="101"/>
         <source>&Cancel</source>
-        <translation type="unfinished"></translation>
+        <translation></translation>

Leere Übersetzung, siehe oben

In companion/src/translations/companion_de.ts:
>      </message>
     <message>
         <location filename="../modeledit/checklistdialog.ui" line="114"/>
         <source>&OK</source>
-        <translation type="unfinished"></translation>
+        <translation></translation>

Leere Übersetzung, siehe oben

In companion/src/translations/companion_de.ts:
>      </message>
     <message>
         <location filename="../modeledit/checklistdialog.ui" line="129"/>
         <source>Please note, the maximum width displayable is radio model limited. Also, renaming the model will break the link to this checklist file.</source>
-        <translation type="unfinished"></translation>

Leere Übersetzung, siehe oben

In companion/src/translations/companion_de.ts:
>      </message>
     <message>
         <location filename="../modeledit/checklistdialog.cpp" line="65"/>
         <source>Open Checklist</source>
-        <translation type="unfinished"></translation>
+        <translation></translation>

Leere Übersetzung, siehe oben

In companion/src/translations/companion_de.ts:
>      </message>
     <message>
         <location filename="../modeledit/checklistdialog.cpp" line="65"/>
         <source>Checklist Files (*.txt)</source>
-        <translation type="unfinished"></translation>
+        <translation></translation>

Leere Übersetzung, siehe oben

In companion/src/translations/companion_de.ts:
> @@ -923,38 +925,40 @@ May be different from firmware language</source>
         <location filename="../modeledit/checklistdialog.cpp" line="102"/>
         <location filename="../modeledit/checklistdialog.cpp" line="110"/>
         <source>Model Checklist</source>
-        <translation type="unfinished"></translation>
+        <translation></translation>

Leere Übersetzung, siehe oben

In companion/src/translations/companion_de.ts:
>      </message>
     <message>
         <location filename="../modeledit/checklistdialog.cpp" line="76"/>
         <source>Cannot open file for writing %1:
 %2.</source>
-        <translation type="unfinished"></tr [...]

2018-05-20 19:25 UTC, kilrah commented
> I am not a fan of this way of marking these strings as finished being translated if there is no real translation but that is ultimately up to however maintains the translations.

Yes, please do not mark missing translations as finished. If no translation is needed it's correct to leave it blank and mark as finished, but if one is needed but not done it should be left unfinished. Otherwise nobody will find what is yet to be done anymore.

2018-05-21 05:44 UTC, hrenz commented
Hall Arne,



habe die Fehler behoben und auch die Translation wieder auf unfinished gesetzt
anstatt immer nur zu bestätigen.


Müsst ID und Instanz nicht exakter heißen:
ID --> Data ID
Instanz --> PhyID


damit es eindeutiger ist 



mfg


H.Renz





.

 

 

 

-----Ursprüngliche Mitteilung----- 
Von: Arne Schwabe <notifications@github.com>
An: opentx/opentx <opentx@noreply.github.com>
Cc: hrenz <hrenz62961@aol.com>; Mention <mention@noreply.github.com>
Verschickt: So, 20. Mai 2018 14:41
Betreff: Re: [opentx/opentx] DE Translation (#5892)



@schwabe requested changes on this pull request.
I have gone through all the changes.
I thought that having an empty translation means that the translation is also empty but it seems that the original English is then used instead.
I am not a fan of this way of marking these strings as finished being translated if there is no real translation but that is ultimately up to however maintains the translations.
There some minor things I noticed with the translation that I commend on each string.

In companion/src/translations/companion_de.ts:
> @@ -355,7 +355,8 @@ Mode 4:
         <location filename="../apppreferencesdialog.ui" line="314"/>
         <source>Set voice language.
 May be different from firmware language</source>
-        <translation type="unfinished"></translation>
+        <translation>Auswahl der Ansagespreche.

Vielleicht eher Sprachausgabe?

In companion/src/translations/companion_de.ts:
> @@ -596,7 +597,7 @@ May be different from firmware language</source>
     <message>
         <location filename="../apppreferencesdialog.cpp" line="117"/>
         <source><p><b>You cannot switch Radio Type or change Build Options while there are unsaved file changes. What do you wish to do?</b></p> <ul><li><i>Save All</i> - Save any open file(s) before saving Settings.<li><li><i>Reset</i> - Revert to the previous Radio Type and Build Options before saving Settings.</li><li><i>Cancel</i> - Return to the Settings editor dialog.</li></ul></source>
-        <translation type="unfinished"></translation>
+        <translation></translation>

Am besten auf unfishined lassen, wenn es nicht übersetzt ist, so bekommt der Nutzt statt der Englischen nur eine leere Fehlermeldung

In companion/src/translations/companion_de.ts:
>  %2.</translation>
     </message>
     <message>
         <location filename="../storage/bineeprom.cpp" line="107"/>
         <source>Invalid binary EEPROM file %1</source>
-        <translation type="unfinished"></translation>
+        <translation>Ungültige Binär EEPROM Datei %1</translation>

Vom Gefühl würde ich binäre EEPROM-Datei sagen

In companion/src/translations/companion_de.ts:
>      </message>
 </context>
 <context>
     <name>CalibrationPanel</name>
     <message>
         <location filename="../generaledit/calibration.cpp" line="44"/>
         <source>Negative span</source>
-        <translation type="unfinished">Neg Bereich</translation>
+        <translation>Neg Bereich</translation>

Im Dialog sollte genug Platz sein um das auszuschreiben. Ich glaube Spanne oder Umfang könnte hier auch passen

In companion/src/translations/companion_de.ts:
>      </message>
     <message>
         <location filename="../generaledit/calibration.cpp" line="44"/>
         <source>Mid value</source>
-        <translation type="unfinished">Mitte Wert</translation>

Wert Mittelstellung

In companion/src/translations/companion_de.ts:
>      </message>
 </context>
 <context>
     <name>CategorizedStorageFormat</name>
     <message>
         <location filename="../storage/categorized.cpp" line="28"/>
         <source>Can't extract RADIO/radio.bin</source>
-        <translation type="unfinished"></translation>
+        <translation></translation>

Leere Übersetzung, siehe oben

In companion/src/translations/companion_de.ts:
>      </message>
     <message>
         <location filename="../storage/categorized.cpp" line="41"/>
         <source>Can't extract RADIO/models.txt</source>
-        <translation type="unfinished"></translation>
+        <translation></translation>

Leere Übersetzung, siehe oben

In companion/src/translations/companion_de.ts:
>      </message>
     <message>
         <location filename="../storage/categorized.cpp" line="85"/>
         <source>Can't extract %1</source>
-        <translation type="unfinished"></translation>
+        <translation></translation>

Leere Übersetzung, siehe oben

In companion/src/translations/companion_de.ts:
>      </message>
     <message>
         <location filename="../storage/categorized.cpp" line="92"/>
         <source>Error loading models</source>
-        <translation type="unfinished"></translation>
+        <translation></translation>

Leere Übersetzung, siehe oben

In companion/src/translations/companion_de.ts:
>      </message>
     <message>
         <location filename="../modeledit/channels.cpp" line="129"/>
         <source>Popup menu available</source>
-        <translation type="unfinished"></translation>
+        <translation>Fenster verfügbar</translation>

Menu ist nicht ganz gleiche wie Fenster.

In companion/src/translations/companion_de.ts:
>      </message>
     <message>
         <location filename="../modeledit/checklistdialog.ui" line="88"/>
         <source>&Import...</source>
-        <translation type="unfinished"></translation>
+        <translation></translation>

Leere Übersetzung, siehe oben

In companion/src/translations/companion_de.ts:
>      </message>
     <message>
         <location filename="../modeledit/checklistdialog.ui" line="101"/>
         <source>&Cancel</source>
-        <translation type="unfinished"></translation>
+        <translation></translation>

Leere Übersetzung, siehe oben

In companion/src/translations/companion_de.ts:
>      </message>
     <message>
         <location filename="../modeledit/checklistdialog.ui" line="114"/>
         <source>&OK</source>
-        <translation type="unfinished"></translation>
+        <translation></translation>

Leere Übersetzung, siehe oben

In companion/src/translations/companion_de.ts:
>      </message>
     <message>
         <location filename="../modeledit/checklistdialog.ui" line="129"/>
         <source>Please note, the maximum width displayable is radio model limited. Also, renaming the model will break the link to this checklist file.</source>
-        <translation type="unfinished"></translation>

Leere Übersetzung, siehe oben

In companion/src/translations/companion_de.ts:
>      </message>
     <message>
         <location filename="../modeledit/checklistdialog.cpp" line="65"/>
         <source>Open Checklist</source>
-        <translation type="unfinished"></translation>
+        <translation></translation>

Leere Übersetzung, siehe oben

In companion/src/translations/companion_de.ts:
>      </message>
     <message>
         <location filename="../modeledit/checklistdialog.cpp" line="65"/>
         <source>Checklist Files (*.txt)</source>
-        <translation type="unfinished"></translation>
+        <translation></translation>

Leere Übersetzung, siehe oben

In companion/src/translations/companion_de.ts:
> @@ -923,38 +925,40 @@ May be different from firmware language</source>
         <location filename="../modeledit/checklistdialog.cpp" line="102"/>
         <location filename="../modeledit/checklistdialog.cpp" line="110"/>
         <source>Model Checklist</source>
-        <translation type="unfinished"></translation>
+        <translation></translation>

Leere Übersetzung, siehe oben

In companion/src/translations/companion_de.ts:
>      </message>
     <message>
         <location filename="../modeledit/checklistdialog.cpp" line="76"/>
         <source>Cannot open file for writing %1:
 %2.</source>
-        <translation type="unfinished"></translation>
+        <translation></translation>

Leere Übersetzung, siehe oben

In companion/src/translations/companion_de.ts:
> @@ -963,77 +967,77 @@ May be different from firmware language</source>
      [...]

2018-05-21 07:39 UTC, schwabe commented
Moin,

Ich sehe leider keine neue Version. Hast du die Datei an deine mail angehängt? Attachments gehen leider bei mail an die Github issue verloren.

2018-05-21 07:54 UTC, bsongis commented
I don't speak german, please press the button when you all agree it's ready :)

2018-05-21 11:47 UTC, kilrah commented
Hmm that last commit is some kind of binary file...

2018-05-21 11:52 UTC, schwabe commented
That was my mistake

2018-05-21 12:28 UTC, merged