Change instance only for FrSky telemetry
opentx/opentx pull request #6671
Opened 2019-08-27 17:25 UTC by 3djc

This fixes conversion of Crossfire sensors for example

2019-08-27 18:37 UTC, raphaelcoeffic commented
I’m still wondering why we are adding `0xE0`. I don’t have the feeling this is even necessary.

2019-08-27 20:09 UTC, bsongis requested changes

2019-08-27 20:09 UTC, bsongis commented on radio/src/storage/conversions/conversions_218_219.cpp
> +    if (oldModel.telemetrySensors[i].type == 0 && (oldModel.moduleData[0].type ==  MODULE_TYPE_XJT_PXX1 || oldModel.moduleData[1].type == MODULE_TYPE_XJT_PXX1))
this test could be done before entering into the loop

2019-08-28 05:57 UTC, bsongis approved these changes
The PR has the rest of the function hidden, I didn't see that it also updated all other fields. Sorry for my negative comment, this PR is perfect

2019-08-28 05:58 UTC, merged