Individual switches boldfaced when 'true' in Logical Switches menu
opentx/opentx pull request #6918
Opened 2019-10-09 20:48 UTC by alexeystn

Implemented feature request #6812

2019-10-09 22:41 UTC, raphaelcoeffic requested changes

2019-10-09 22:41 UTC, raphaelcoeffic commented on radio/src/gui/128x64/model_logical_switches.cpp
> +          drawSwitch(CSWONE_2ND_COLUMN, y, v1_val, attr | ((getSwitch(v1_val) && v1_val) ? BOLD : 0));
the condition should be reversed: `v1_val && getSwitch(v1_val)`. This avoids evaluating `getSwitch()` for nothing.

2019-10-09 22:41 UTC, raphaelcoeffic commented on radio/src/gui/128x64/model_logical_switches.cpp
> +          drawSwitch(CSWONE_2ND_COLUMN, y, cs->v2, attr | ((getSwitch(cs->v2) && cs->v2) ? BOLD : 0));
same everywhere else

2019-10-09 22:41 UTC, raphaelcoeffic commented on radio/src/gui/128x64/model_logical_switches.cpp
> +        drawSwitch(CSWONE_2ND_COLUMN, y, cs->andsw, attr | ((getSwitch(cs->andsw) && cs->andsw) ? BOLD : 0));
same everywhere else

2019-10-09 22:41 UTC, raphaelcoeffic commented on radio/src/gui/128x64/model_logical_switches.cpp
> +        drawSwitch(CSW_2ND_COLUMN, y, cs->v1, (getSwitch(cs->v1) && cs->v1) ? BOLD : 0);
same everywhere else

2019-10-10 13:46 UTC, bsongis commented
To avoid duplicated code I think you could add a parameter to `drawSwitch`? Or introduce a new function?

2019-10-28 14:13 UTC, bsongis commented
Done in #7000

2019-10-28 14:13 UTC, closed without merging